### ISSUE TITLE
Error while setting up midea_ac

### ISSUE THREAD

**Issue by zawias** [WMP/midea-ac-py#5]
I have such a problem. Anyone can help?

```
2021-07-14 00:12:01 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac/climate.py", line 75, in async_setup_platform
    device = ac(device_ip, int(device_id))
TypeError: __init__() missing 1 required positional argument: 'device_port'
```

**Comment by zawias** [comment]
I installed the latest version of msmart and that was a problem.

**Comment by titogarrido** [comment]
Hi! How did you solve it? I have installed it today on Hassio clonning it from https://github.com/WMP/midea-ac-py/tree/support-8370 but I am receiving:

```
2021-07-23 12:57:16 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac/climate.py", line 73, in async_setup_platform
    device = ac(device_ip, int(device_id))
TypeError: __init__() missing 1 required positional argument: 'device_port'
```
